[log]
level = "debug"
output = "stdout"

[database]
host = "192.168.1.4"
port = 5432
user = "postgres"
password = "123aaa"

[mq]
chanbuf = 1024
host = "127.0.0.1"
port = 4222

[jwt]
algorithm = "RS256"
encode_key = "file:etc/jwt-prikey.pem"
decode_key = "file:etc/jwt-pubkey.pem"
