[log]
level = "debug"
output = "stdout"
enable_level = true
enable_file = true
enable_line = true
enable_thread_name = false
enable_thread_id = false

[database]
host = "192.168.1.4"
port = 5432
user = "postgres"
password = "123aaa"
# optional config
max_conn = 10
min_conn = 3
# comment idle_timeout for no timeout
idle_timeout = "1h"

[mq]
chanbuf = 1024
host = "127.0.0.1"
port = 4222

[jwt]
algorithm = "RS256"
encode_key = "file:etc/jwt-prikey.pem"
decode_key = "file:etc/jwt-pubkey.pem"
