[log]
level = "debug"
output = "stdout"
enable_level = true
enable_file = true
enable_line = true
enable_thread_name = false
enable_thread_id = false

[database]
host = "192.168.1.6"
port = 5432
user = "postgres"
password = "password"
# optional config
max_conn = 10
min_conn = 3
# comment idle_timeout for no timeout
# idle_timeout = "1h"

[mq]
chanbuf = 1024
host = "192.168.1.6"
port = 4222
#optional config
conn_timeout = "5s"
client_capacity = 128
subscription_capacity = 1024
request_timeout = "10s"
ping_interval = "60s"
flush_interval = "50ms"

[jwt]
algorithm = "RS256"
encode_key = "file:etc/jwt-prikey.pem"
decode_key = "file:etc/jwt-pubkey.pem"

[etcd]
endpoints = ["localhost:2379"]
conn_timeout = "5s"
request_timeout = "3s"
keepalive_interval = "10s"
keepalive_timeout = "3s"
keepalive_idle = true